-- ============================================================
-- VAULTIO — Estructura de Base de Datos (DDL)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- SETUP INICIAL
-- ────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ────────────────────────────────────────────────────────────
-- TABLAS
-- ────────────────────────────────────────────────────────────

-- ========================
-- CATÁLOGOS / ESTRUCTURALES
-- ========================

CREATE TABLE IF NOT EXISTS institutions (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(80)     NOT NULL,
    acronym         VARCHAR(20),
    email_domain    VARCHAR(40),
    logo_url        TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_institutions_name         UNIQUE (name),
    CONSTRAINT uq_institutions_email_domain UNIQUE (email_domain)
);


CREATE TABLE IF NOT EXISTS careers (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(20)     NOT NULL,
    name            VARCHAR(80)     NOT NULL,
    study_plan      VARCHAR(20)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    institution_id  INTEGER         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_careers_institution_code_plan UNIQUE (institution_id, code, study_plan)
);


CREATE TABLE IF NOT EXISTS courses (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(20)     NOT NULL,
    name            VARCHAR(80)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_courses_code UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS course_careers (
    course_id       INTEGER         NOT NULL,
    career_id       INTEGER         NOT NULL,

    PRIMARY KEY (course_id, career_id)
);


CREATE TABLE IF NOT EXISTS professors (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR(60)     NOT NULL,
    last_name       VARCHAR(80)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS professor_courses (
    professor_id    INTEGER         NOT NULL,
    course_id       INTEGER         NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (professor_id, course_id)
);


CREATE TABLE IF NOT EXISTS resource_types (
    id              SMALLINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(30)     NOT NULL,
    description     VARCHAR(255),

    PRIMARY KEY (id),
    CONSTRAINT uq_resource_types_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS academic_periods (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(40)     NOT NULL,
    year            INTEGER,
    institution_id  INTEGER,

    PRIMARY KEY (id),
    CONSTRAINT chk_academic_periods_year CHECK (year BETWEEN 2000 AND 2100)
);


-- ========================
-- USUARIOS, AUTH & RBAC
-- ========================

CREATE TABLE IF NOT EXISTS users (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    username            VARCHAR(30)     NOT NULL,
    first_name          VARCHAR(30)     NOT NULL,
    last_name           VARCHAR(255)    NOT NULL,
    -- Se dejó como TEXT porque pueden ser de un largo impredescible.
    photo_url           TEXT,
    bio                 VARCHAR(255),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    reputation_score    INTEGER         NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    CONSTRAINT uq_users_username        UNIQUE (username),
    CONSTRAINT chk_users_reputation     CHECK (reputation_score >= 0)
);

COMMENT ON COLUMN users.photo_url IS 'Se dejó como TEXT porque pueden ser de un largo impredescible.';


CREATE TABLE IF NOT EXISTS identities (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    provider_name   VARCHAR(60)     NOT NULL,
    provider_uid    VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    last_login      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    user_id         UUID            NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_identities_provider_uid UNIQUE (provider_name, provider_uid)
);


CREATE TABLE IF NOT EXISTS roles (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS permissions (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS user_careers (
    user_id         UUID            NOT NULL,
    career_id       INTEGER         NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (user_id, career_id)
);

CREATE TABLE IF NOT EXISTS user_courses (
    user_id         UUID            NOT NULL,
    course_id       INTEGER         NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, course_id)
);


CREATE TABLE IF NOT EXISTS user_roles (
    role_id         INTEGER         NOT NULL,
    user_id         UUID            NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (role_id, user_id)
);


CREATE TABLE IF NOT EXISTS role_permissions (
    permission_id   INTEGER         NOT NULL,
    role_id         INTEGER         NOT NULL,

    PRIMARY KEY (permission_id, role_id)
);


CREATE TABLE IF NOT EXISTS user_permissions (
    permission_id   INTEGER         NOT NULL,
    user_id         UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (permission_id, user_id)
);


-- ========================
-- CONTENIDO PRINCIPAL
-- ========================

CREATE TABLE IF NOT EXISTS resources (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    title               VARCHAR(80)     NOT NULL,
    description         TEXT            NOT NULL,
    tags                VARCHAR(60)     ARRAY,
    storage_provider    VARCHAR(30)     NOT NULL DEFAULT 'minio',
    storage_bucket      VARCHAR(255)    NOT NULL,
    storage_key         TEXT            NOT NULL,
    original_filename   VARCHAR(255)    NOT NULL,
    mime_type           VARCHAR(120)    NOT NULL,
    checksum_sha256     CHAR(64),
    upload_status       VARCHAR(20)     NOT NULL DEFAULT 'ready',
    file_url            TEXT,
    file_size           BIGINT,
    file_extension      VARCHAR(10),
    views_count         BIGINT          NOT NULL DEFAULT 0,
    downloads_count     BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    professor_id        INTEGER,
    user_id             UUID            NOT NULL,
    academic_period_id  INTEGER,
    course_id           INTEGER         NOT NULL,
    resource_type_id    SMALLINT        NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_resources_storage_object  UNIQUE (storage_provider, storage_bucket, storage_key),
    CONSTRAINT chk_resources_file_size      CHECK (file_size >= 0),
    CONSTRAINT chk_resources_views_count    CHECK (views_count >= 0),
    CONSTRAINT chk_resources_downloads_count CHECK (downloads_count >= 0),
    CONSTRAINT chk_resources_storage_provider CHECK (storage_provider IN ('firebase_storage', 'minio', 'local', 's3', 'external')),
    CONSTRAINT chk_resources_storage_bucket CHECK (LENGTH(TRIM(storage_bucket)) > 0),
    CONSTRAINT chk_resources_storage_key    CHECK (LENGTH(TRIM(storage_key)) > 0),
    CONSTRAINT chk_resources_upload_status  CHECK (upload_status IN ('pending', 'ready', 'failed', 'deleted')),
    CONSTRAINT chk_resources_checksum_sha256 CHECK (
        checksum_sha256 IS NULL
        OR checksum_sha256 ~ '^[0-9a-f]{64}$'
    )
);


CREATE TABLE IF NOT EXISTS comments (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    content         VARCHAR(512)    NOT NULL,
    resource_id     UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    user_id         UUID            NOT NULL,
    parent_id       UUID,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS ratings (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    stars           SMALLINT        NOT NULL,
    resource_id     UUID            NOT NULL,
    user_id         UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    CONSTRAINT uq_ratings_user_resource UNIQUE (user_id, resource_id),
    CONSTRAINT chk_ratings_stars        CHECK (stars BETWEEN 1 AND 5)
);


-- ========================
-- INTERACCIONES
-- ========================

CREATE TABLE IF NOT EXISTS saved_resources (
    user_id         UUID            NOT NULL,
    resource_id     UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, resource_id)
);


CREATE TABLE IF NOT EXISTS user_downloads (
    id              BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id         UUID            NOT NULL,
    resource_id     UUID            NOT NULL,
    downloaded_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS comment_votes (
    user_id         UUID            NOT NULL,
    comment_id      UUID            NOT NULL,
    vote_type       SMALLINT        NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, comment_id),
    CONSTRAINT chk_comment_votes_type CHECK (vote_type IN (-1, 1))
);


-- ========================
-- REPORTES / MODERACIÓN
-- ========================

CREATE TABLE IF NOT EXISTS reports (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    reason              VARCHAR(255)    NOT NULL,
    status              VARCHAR(30)     NOT NULL DEFAULT 'pending',
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    resolved_at         TIMESTAMPTZ,
    admin_notes         VARCHAR(512),
    reporter_id         UUID            NOT NULL,
    reported_user_id    UUID,
    resource_id         UUID,
    comment_id          UUID,

    PRIMARY KEY (id),
    CONSTRAINT chk_reports_status CHECK (
        status IN ('pending', 'reviewing', 'resolved', 'dismissed')
    ),
    CONSTRAINT chk_reports_single_target CHECK (
        ((reported_user_id IS NOT NULL)::INTEGER
        + (resource_id IS NOT NULL)::INTEGER
        + (comment_id IS NOT NULL)::INTEGER) = 1
    )
);


-- ========================
-- AUDITORÍA
-- ========================

CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    table_name      VARCHAR(60)     NOT NULL,
    record_id       TEXT            NOT NULL,
    action          VARCHAR(10)     NOT NULL,
    old_data        JSONB,
    new_data        JSONB,
    changed_by      UUID,
    changed_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    CONSTRAINT chk_audit_log_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);


-- ────────────────────────────────────────────────────────────
-- FOREIGN KEYS
-- ────────────────────────────────────────────────────────────

-- Careers → Institutions
ALTER TABLE careers
    ADD CONSTRAINT fk_careers_institution
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Course_Careers → Courses / Careers
ALTER TABLE course_careers
    ADD CONSTRAINT fk_course_careers_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE course_careers
    ADD CONSTRAINT fk_course_careers_career
    FOREIGN KEY (career_id) REFERENCES careers(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Professor_Courses → Professors / Courses
ALTER TABLE professor_courses
    ADD CONSTRAINT fk_professor_courses_professor
    FOREIGN KEY (professor_id) REFERENCES professors(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE professor_courses
    ADD CONSTRAINT fk_professor_courses_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Academic_Periods → Institutions
ALTER TABLE academic_periods
    ADD CONSTRAINT fk_academic_periods_institution
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- Identities → Users
ALTER TABLE identities
    ADD CONSTRAINT fk_identities_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Careers → Users / Careers
ALTER TABLE user_careers
    ADD CONSTRAINT fk_user_careers_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_careers
    ADD CONSTRAINT fk_user_careers_career
    FOREIGN KEY (career_id) REFERENCES careers(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_courses
    ADD CONSTRAINT fk_user_courses_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_courses
    ADD CONSTRAINT fk_user_courses_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Roles → Users / Roles
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Role_Permissions → Permissions / Roles
ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_role
    FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Permissions → Permissions / Users
ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Resources → Professors / Users / Academic_Periods / Courses / Resource_Types
ALTER TABLE resources
    ADD CONSTRAINT fk_resources_professor
    FOREIGN KEY (professor_id) REFERENCES professors(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_academic_period
    FOREIGN KEY (academic_period_id) REFERENCES academic_periods(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_resource_type
    FOREIGN KEY (resource_type_id) REFERENCES resource_types(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Comments → Resources / Users / Comments (self-ref)
ALTER TABLE comments
    ADD CONSTRAINT fk_comments_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_parent
    FOREIGN KEY (parent_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Ratings → Resources / Users
ALTER TABLE ratings
    ADD CONSTRAINT fk_ratings_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ratings
    ADD CONSTRAINT fk_ratings_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Saved_Resources → Users / Resources
ALTER TABLE saved_resources
    ADD CONSTRAINT fk_saved_resources_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE saved_resources
    ADD CONSTRAINT fk_saved_resources_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Downloads → Users / Resources
ALTER TABLE user_downloads
    ADD CONSTRAINT fk_user_downloads_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_downloads
    ADD CONSTRAINT fk_user_downloads_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Comment_Votes → Users / Comments
ALTER TABLE comment_votes
    ADD CONSTRAINT fk_comment_votes_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comment_votes
    ADD CONSTRAINT fk_comment_votes_comment
    FOREIGN KEY (comment_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Reports → Users (reporter) / Users (reported) / Resources / Comments
ALTER TABLE reports
    ADD CONSTRAINT fk_reports_reporter
    FOREIGN KEY (reporter_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_reported_user
    FOREIGN KEY (reported_user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_comment
    FOREIGN KEY (comment_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE SET NULL;


-- ────────────────────────────────────────────────────────────
-- ÍNDICES
-- ────────────────────────────────────────────────────────────

-- === FK look-ups (aceleran JOINs y ON DELETE) ===
CREATE INDEX idx_careers_institution        ON careers(institution_id);
CREATE INDEX idx_course_careers_course      ON course_careers(course_id);
CREATE INDEX idx_course_careers_career      ON course_careers(career_id);
CREATE INDEX idx_professor_courses_prof     ON professor_courses(professor_id);
CREATE INDEX idx_professor_courses_course   ON professor_courses(course_id);
CREATE INDEX idx_academic_periods_inst      ON academic_periods(institution_id);
CREATE INDEX idx_identities_user            ON identities(user_id);
CREATE INDEX idx_user_careers_user          ON user_careers(user_id);
CREATE INDEX idx_user_careers_career        ON user_careers(career_id);
CREATE INDEX idx_user_courses_user          ON user_courses(user_id);
CREATE INDEX idx_user_courses_course        ON user_courses(course_id);
CREATE INDEX idx_user_roles_user            ON user_roles(user_id);
CREATE INDEX idx_user_roles_role            ON user_roles(role_id);
CREATE INDEX idx_role_permissions_role      ON role_permissions(role_id);
CREATE INDEX idx_user_permissions_user      ON user_permissions(user_id);
CREATE INDEX idx_resources_user             ON resources(user_id);
CREATE INDEX idx_resources_course           ON resources(course_id);
CREATE INDEX idx_resources_type             ON resources(resource_type_id);
CREATE INDEX idx_resources_professor        ON resources(professor_id);
CREATE INDEX idx_resources_period           ON resources(academic_period_id);
CREATE INDEX idx_resources_storage_key      ON resources(storage_provider, storage_bucket, storage_key);
CREATE INDEX idx_comments_resource          ON comments(resource_id);
CREATE INDEX idx_comments_user              ON comments(user_id);
CREATE INDEX idx_comments_parent            ON comments(parent_id);
CREATE INDEX idx_ratings_resource           ON ratings(resource_id);
CREATE INDEX idx_ratings_user               ON ratings(user_id);
CREATE INDEX idx_saved_resources_resource   ON saved_resources(resource_id);
CREATE INDEX idx_user_downloads_user        ON user_downloads(user_id);
CREATE INDEX idx_user_downloads_resource    ON user_downloads(resource_id);
CREATE INDEX idx_comment_votes_comment      ON comment_votes(comment_id);
CREATE INDEX idx_reports_reporter           ON reports(reporter_id);
CREATE INDEX idx_reports_reported_user      ON reports(reported_user_id);
CREATE INDEX idx_reports_resource           ON reports(resource_id);
CREATE INDEX idx_reports_comment            ON reports(comment_id);

-- === Búsqueda textual / lookup ===
CREATE INDEX idx_users_username             ON users(username);
CREATE INDEX idx_identities_email           ON identities(email);
CREATE INDEX idx_courses_code               ON courses(code);
CREATE INDEX idx_careers_code               ON careers(code);
CREATE INDEX idx_resources_title            ON resources(title);
-- Wrapper inmutable porque to_tsvector(regconfig, text) es STABLE en Postgres
-- y los indices/expresiones generadas requieren IMMUTABLE.
CREATE OR REPLACE FUNCTION vaultio_resource_search_vector(
    p_title TEXT,
    p_description TEXT,
    p_tags TEXT[]
) RETURNS tsvector AS $$
    SELECT to_tsvector(
        'spanish'::regconfig,
        COALESCE(p_title, '') || ' ' ||
        COALESCE(p_description, '') || ' ' ||
        COALESCE(array_to_string(p_tags, ' '), '')
    );
$$ LANGUAGE SQL IMMUTABLE;

CREATE INDEX idx_resources_search ON resources USING GIN (
    vaultio_resource_search_vector(title, description, tags)
);

-- === Filtros frecuentes ===
CREATE INDEX idx_resources_active           ON resources(is_active) WHERE is_active = TRUE;
CREATE INDEX idx_resources_created          ON resources(created_at DESC);
CREATE INDEX idx_reports_status_pending     ON reports(status) WHERE status = 'pending';

-- === GIN para búsqueda en array de tags ===
CREATE INDEX idx_resources_tags             ON resources USING GIN(tags);

-- === Auditoría ===
CREATE INDEX idx_audit_log_table            ON audit_log(table_name);
CREATE INDEX idx_audit_log_record           ON audit_log(record_id);
CREATE INDEX idx_audit_log_date             ON audit_log(changed_at DESC);

-- ===========================================================
-- LOGIC (functions and triggers)
-- ===========================================================
-- ============================================================
-- VAULTIO — Lógica de Base de Datos (Funciones, Triggers, SPs)
-- Archivo: logic.sql
-- ============================================================


-- ────────────────────────────────────────────────────────────
-- FUNCIONES DE TRIGGER
-- ────────────────────────────────────────────────────────────

-- 1. Auto-update de updated_at
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER trg_resources_updated_at
    BEFORE UPDATE ON resources
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();

CREATE TRIGGER trg_comments_updated_at
    BEFORE UPDATE ON comments
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();


-- 2. Incrementar downloads_count al registrar descarga
CREATE OR REPLACE FUNCTION trg_increment_downloads()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE resources
        SET downloads_count = downloads_count + 1
    WHERE id = NEW.resource_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_user_downloads_count
    AFTER INSERT ON user_downloads
    FOR EACH ROW EXECUTE FUNCTION trg_increment_downloads();


-- 3. Prevenir que un usuario califique su propio recurso
CREATE OR REPLACE FUNCTION trg_prevent_self_rating()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.user_id = (SELECT user_id FROM resources WHERE id = NEW.resource_id) THEN
        RAISE EXCEPTION 'Un usuario no puede calificar su propio recurso.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ratings_no_self
    BEFORE INSERT OR UPDATE ON ratings
    FOR EACH ROW EXECUTE FUNCTION trg_prevent_self_rating();


-- 4. Prevenir que un usuario se reporte a sí mismo
CREATE OR REPLACE FUNCTION trg_prevent_self_report()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.reporter_id IS NOT NULL
       AND NEW.reported_user_id IS NOT NULL
       AND NEW.reporter_id = NEW.reported_user_id THEN
        RAISE EXCEPTION 'Un usuario no puede reportarse a sí mismo.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reports_no_self
    BEFORE INSERT ON reports
    FOR EACH ROW EXECUTE FUNCTION trg_prevent_self_report();


-- 5. Auditoría genérica
CREATE OR REPLACE FUNCTION trg_audit_log()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO audit_log(table_name, record_id, action, old_data, new_data)
    VALUES (
        TG_TABLE_NAME,
        COALESCE(NEW.id::TEXT, OLD.id::TEXT),
        TG_OP,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END
    );
    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

-- Auditoría en tablas críticas
CREATE TRIGGER trg_audit_users
    AFTER INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION trg_audit_log();

CREATE TRIGGER trg_audit_resources
    AFTER INSERT OR UPDATE OR DELETE ON resources
    FOR EACH ROW EXECUTE FUNCTION trg_audit_log();

CREATE TRIGGER trg_audit_reports
    AFTER INSERT OR UPDATE OR DELETE ON reports
    FOR EACH ROW EXECUTE FUNCTION trg_audit_log();

CREATE TRIGGER trg_audit_comments
    AFTER INSERT OR UPDATE OR DELETE ON comments
    FOR EACH ROW EXECUTE FUNCTION trg_audit_log();

CREATE TRIGGER trg_audit_ratings
    AFTER INSERT OR UPDATE OR DELETE ON ratings
    FOR EACH ROW EXECUTE FUNCTION trg_audit_log();


-- ────────────────────────────────────────────────────────────
-- STORED FUNCTIONS (Lógica de Negocio)
-- ────────────────────────────────────────────────────────────

-- 1. Promedio de rating de un recurso
CREATE OR REPLACE FUNCTION fn_resource_avg_rating(p_resource_id UUID)
RETURNS NUMERIC(3,2) AS $$
    SELECT COALESCE(AVG(stars)::NUMERIC(3,2), 0)
    FROM ratings
    WHERE resource_id = p_resource_id;
$$ LANGUAGE sql STABLE;


-- 2. Recalcular reputación de un usuario
CREATE OR REPLACE FUNCTION fn_recalc_reputation(p_user_id UUID)
RETURNS VOID AS $$
DECLARE
    v_score INTEGER;
BEGIN
    SELECT COALESCE(
        SUM(
            CASE
                WHEN sub.avg_stars >= 4 THEN 3
                WHEN sub.avg_stars >= 3 THEN 1
                ELSE 0
            END
        ), 0)
    INTO v_score
    FROM (
        SELECT res.id, AVG(rat.stars) AS avg_stars
        FROM resources res
        JOIN ratings rat ON rat.resource_id = res.id
        WHERE res.user_id = p_user_id
          AND res.is_active = TRUE
        GROUP BY res.id
    ) sub;

    UPDATE users
        SET reputation_score = v_score
    WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql;


-- 3. Soft-delete en cascada para un recurso
CREATE OR REPLACE FUNCTION fn_soft_delete_resource(p_resource_id UUID)
RETURNS VOID AS $$
BEGIN
    UPDATE resources
        SET is_active = FALSE, updated_at = NOW()
    WHERE id = p_resource_id;

    UPDATE comments
        SET is_active = FALSE, updated_at = NOW()
    WHERE resource_id = p_resource_id;
END;
$$ LANGUAGE plpgsql;


-- 4. Estadísticas completas de un recurso
CREATE OR REPLACE FUNCTION fn_resource_stats(p_resource_id UUID)
RETURNS TABLE (
    avg_rating      NUMERIC(3,2),
    total_ratings   BIGINT,
    total_comments  BIGINT,
    total_downloads BIGINT,
    total_saves     BIGINT
) AS $$
    SELECT
        COALESCE(AVG(rat.stars)::NUMERIC(3,2), 0)  AS avg_rating,
        COUNT(DISTINCT rat.id)                       AS total_ratings,
        (SELECT COUNT(*) FROM comments c
            WHERE c.resource_id = p_resource_id AND c.is_active = TRUE),
        (SELECT COUNT(*) FROM user_downloads d
            WHERE d.resource_id = p_resource_id),
        (SELECT COUNT(*) FROM saved_resources s
            WHERE s.resource_id = p_resource_id)
    FROM ratings rat
    WHERE rat.resource_id = p_resource_id;
$$ LANGUAGE sql STABLE;
