-- ============================================================
-- VAULTIO — Estructura de Base de Datos (DDL)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- SETUP INICIAL
-- ────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ────────────────────────────────────────────────────────────
-- TABLAS
-- ────────────────────────────────────────────────────────────

-- ========================
-- CATÁLOGOS / ESTRUCTURALES
-- ========================

CREATE TABLE IF NOT EXISTS institutions (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(80)     NOT NULL,
    acronym         VARCHAR(20),
    email_domain    VARCHAR(40),
    logo_url        TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_institutions_name         UNIQUE (name),
    CONSTRAINT uq_institutions_email_domain UNIQUE (email_domain)
);


CREATE TABLE IF NOT EXISTS careers (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(20)     NOT NULL,
    name            VARCHAR(80)     NOT NULL,
    study_plan      VARCHAR(20)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    institution_id  INTEGER         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_careers_plan_per_institution UNIQUE (institution_id, study_plan),
    CONSTRAINT uq_careers_code                 UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS courses (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(20)     NOT NULL,
    name            VARCHAR(80)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_courses_code UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS course_careers (
    course_id       INTEGER         NOT NULL,
    career_id       INTEGER         NOT NULL,

    PRIMARY KEY (course_id, career_id)
);


CREATE TABLE IF NOT EXISTS professors (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR(60)     NOT NULL,
    last_name       VARCHAR(80)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS professor_courses (
    professor_id    INTEGER         NOT NULL,
    course_id       INTEGER         NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (professor_id, course_id)
);


CREATE TABLE IF NOT EXISTS resource_types (
    id              SMALLINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(30)     NOT NULL,
    description     VARCHAR(255),

    PRIMARY KEY (id),
    CONSTRAINT uq_resource_types_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS academic_periods (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(40)     NOT NULL,
    year            INTEGER,
    institution_id  INTEGER,

    PRIMARY KEY (id),
    CONSTRAINT chk_academic_periods_year CHECK (year BETWEEN 2000 AND 2100)
);


-- ========================
-- USUARIOS, AUTH & RBAC
-- ========================

CREATE TABLE IF NOT EXISTS users (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    username            VARCHAR(30)     NOT NULL,
    first_name          VARCHAR(30)     NOT NULL,
    last_name           VARCHAR(255)    NOT NULL,
    -- Se dejó como TEXT porque pueden ser de un largo impredescible.
    photo_url           TEXT,
    bio                 VARCHAR(255),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    reputation_score    INTEGER         NOT NULL DEFAULT 0,

    PRIMARY KEY (id),
    CONSTRAINT uq_users_username        UNIQUE (username),
    CONSTRAINT chk_users_reputation     CHECK (reputation_score >= 0)
);

COMMENT ON COLUMN users.photo_url IS 'Se dejó como TEXT porque pueden ser de un largo impredescible.';


CREATE TABLE IF NOT EXISTS identities (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    provider_name   VARCHAR(60)     NOT NULL,
    provider_uid    VARCHAR(255)    NOT NULL,
    email           VARCHAR(255)    NOT NULL,
    last_login      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    user_id         UUID            NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_identities_provider_uid UNIQUE (provider_uid)
);


CREATE TABLE IF NOT EXISTS roles (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS permissions (
    id              INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(30)     NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id),
    CONSTRAINT uq_permissions_code UNIQUE (code)
);


CREATE TABLE IF NOT EXISTS user_careers (
    user_id         UUID            NOT NULL,
    career_id       INTEGER         NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (user_id, career_id)
);


CREATE TABLE IF NOT EXISTS user_roles (
    role_id         INTEGER         NOT NULL,
    user_id         UUID            NOT NULL,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (role_id, user_id)
);


CREATE TABLE IF NOT EXISTS role_permissions (
    permission_id   INTEGER         NOT NULL,
    role_id         INTEGER         NOT NULL,

    PRIMARY KEY (permission_id, role_id)
);


CREATE TABLE IF NOT EXISTS user_permissions (
    permission_id   INTEGER         NOT NULL,
    user_id         UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    PRIMARY KEY (permission_id, user_id)
);


-- ========================
-- CONTENIDO PRINCIPAL
-- ========================

CREATE TABLE IF NOT EXISTS resources (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    title               VARCHAR(80)     NOT NULL,
    description         TEXT            NOT NULL,
    tags                VARCHAR(60)     ARRAY,
    file_url            TEXT            NOT NULL,
    file_size           BIGINT,
    file_extension      VARCHAR(10),
    views_count         BIGINT          NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,
    professor_id        INTEGER,
    user_id             UUID            NOT NULL,
    academic_period_id  INTEGER,
    course_id           INTEGER         NOT NULL,
    resource_type_id    INTEGER         NOT NULL,

    PRIMARY KEY (id),
    CONSTRAINT chk_resources_file_size      CHECK (file_size > 0),
    CONSTRAINT chk_resources_views_count    CHECK (views_count >= 0)
);


CREATE TABLE IF NOT EXISTS comments (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    content         VARCHAR(512)    NOT NULL,
    resource_id     UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    user_id         UUID            NOT NULL,
    parent_id       UUID,

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS ratings (
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),
    stars           SMALLINT        NOT NULL,
    resource_id     UUID            NOT NULL,
    user_id         UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    CONSTRAINT uq_ratings_user_resource UNIQUE (user_id, resource_id),
    CONSTRAINT chk_ratings_stars        CHECK (stars BETWEEN 1 AND 5)
);


-- ========================
-- INTERACCIONES
-- ========================

CREATE TABLE IF NOT EXISTS saved_resources (
    user_id         UUID            NOT NULL,
    resource_id     UUID            NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, resource_id)
);


CREATE TABLE IF NOT EXISTS user_downloads (
    id              BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id         UUID            NOT NULL,
    resource_id     UUID            NOT NULL,
    downloaded_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS comment_votes (
    user_id         UUID            NOT NULL,
    comment_id      UUID            NOT NULL,
    vote_type       SMALLINT        NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, comment_id),
    CONSTRAINT chk_comment_votes_type CHECK (vote_type IN (-1, 1))
);


-- ========================
-- REPORTES / MODERACIÓN
-- ========================

CREATE TABLE IF NOT EXISTS reports (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    reason              VARCHAR(255)    NOT NULL,
    status              VARCHAR(30)     NOT NULL DEFAULT 'pending',
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    resolved_at         TIMESTAMPTZ,
    admin_notes         VARCHAR(512),
    reporter_id         UUID            NOT NULL,
    reported_user_id    UUID,
    resource_id         UUID,
    comment_id          UUID,

    PRIMARY KEY (id),
    CONSTRAINT chk_reports_status CHECK (
        status IN ('pending', 'reviewing', 'resolved', 'dismissed')
    ),
    CONSTRAINT chk_reports_has_target CHECK (
        reported_user_id IS NOT NULL
        OR resource_id IS NOT NULL
        OR comment_id IS NOT NULL
    )
);


-- ========================
-- AUDITORÍA
-- ========================

CREATE TABLE IF NOT EXISTS audit_log (
    id              BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    table_name      VARCHAR(60)     NOT NULL,
    record_id       TEXT            NOT NULL,
    action          VARCHAR(10)     NOT NULL,
    old_data        JSONB,
    new_data        JSONB,
    changed_by      UUID,
    changed_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    PRIMARY KEY (id),
    CONSTRAINT chk_audit_log_action CHECK (action IN ('INSERT', 'UPDATE', 'DELETE'))
);


-- ────────────────────────────────────────────────────────────
-- FOREIGN KEYS
-- ────────────────────────────────────────────────────────────

-- Careers → Institutions
ALTER TABLE careers
    ADD CONSTRAINT fk_careers_institution
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Course_Careers → Courses / Careers
ALTER TABLE course_careers
    ADD CONSTRAINT fk_course_careers_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE course_careers
    ADD CONSTRAINT fk_course_careers_career
    FOREIGN KEY (career_id) REFERENCES careers(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Professor_Courses → Professors / Courses
ALTER TABLE professor_courses
    ADD CONSTRAINT fk_professor_courses_professor
    FOREIGN KEY (professor_id) REFERENCES professors(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE professor_courses
    ADD CONSTRAINT fk_professor_courses_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Academic_Periods → Institutions
ALTER TABLE academic_periods
    ADD CONSTRAINT fk_academic_periods_institution
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

-- Identities → Users
ALTER TABLE identities
    ADD CONSTRAINT fk_identities_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Careers → Users / Careers
ALTER TABLE user_careers
    ADD CONSTRAINT fk_user_careers_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_careers
    ADD CONSTRAINT fk_user_careers_career
    FOREIGN KEY (career_id) REFERENCES careers(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Roles → Users / Roles
ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Role_Permissions → Permissions / Roles
ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE role_permissions
    ADD CONSTRAINT fk_role_permissions_role
    FOREIGN KEY (role_id) REFERENCES roles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Permissions → Permissions / Users
ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_permission
    FOREIGN KEY (permission_id) REFERENCES permissions(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Resources → Professors / Users / Academic_Periods / Courses / Resource_Types
ALTER TABLE resources
    ADD CONSTRAINT fk_resources_professor
    FOREIGN KEY (professor_id) REFERENCES professors(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_academic_period
    FOREIGN KEY (academic_period_id) REFERENCES academic_periods(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_course
    FOREIGN KEY (course_id) REFERENCES courses(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE resources
    ADD CONSTRAINT fk_resources_resource_type
    FOREIGN KEY (resource_type_id) REFERENCES resource_types(id)
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Comments → Resources / Users / Comments (self-ref)
ALTER TABLE comments
    ADD CONSTRAINT fk_comments_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_parent
    FOREIGN KEY (parent_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Ratings → Resources / Users
ALTER TABLE ratings
    ADD CONSTRAINT fk_ratings_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ratings
    ADD CONSTRAINT fk_ratings_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Saved_Resources → Users / Resources
ALTER TABLE saved_resources
    ADD CONSTRAINT fk_saved_resources_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE saved_resources
    ADD CONSTRAINT fk_saved_resources_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- User_Downloads → Users / Resources
ALTER TABLE user_downloads
    ADD CONSTRAINT fk_user_downloads_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE user_downloads
    ADD CONSTRAINT fk_user_downloads_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Comment_Votes → Users / Comments
ALTER TABLE comment_votes
    ADD CONSTRAINT fk_comment_votes_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE comment_votes
    ADD CONSTRAINT fk_comment_votes_comment
    FOREIGN KEY (comment_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

-- Reports → Users (reporter) / Users (reported) / Resources / Comments
ALTER TABLE reports
    ADD CONSTRAINT fk_reports_reporter
    FOREIGN KEY (reporter_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_reported_user
    FOREIGN KEY (reported_user_id) REFERENCES users(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_resource
    FOREIGN KEY (resource_id) REFERENCES resources(id)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE reports
    ADD CONSTRAINT fk_reports_comment
    FOREIGN KEY (comment_id) REFERENCES comments(id)
    ON UPDATE CASCADE ON DELETE SET NULL;


-- ────────────────────────────────────────────────────────────
-- ÍNDICES
-- ────────────────────────────────────────────────────────────

-- === FK look-ups (aceleran JOINs y ON DELETE) ===
CREATE INDEX idx_careers_institution        ON careers(institution_id);
CREATE INDEX idx_course_careers_course      ON course_careers(course_id);
CREATE INDEX idx_course_careers_career      ON course_careers(career_id);
CREATE INDEX idx_professor_courses_prof     ON professor_courses(professor_id);
CREATE INDEX idx_professor_courses_course   ON professor_courses(course_id);
CREATE INDEX idx_academic_periods_inst      ON academic_periods(institution_id);
CREATE INDEX idx_identities_user            ON identities(user_id);
CREATE INDEX idx_user_careers_user          ON user_careers(user_id);
CREATE INDEX idx_user_careers_career        ON user_careers(career_id);
CREATE INDEX idx_user_roles_user            ON user_roles(user_id);
CREATE INDEX idx_user_roles_role            ON user_roles(role_id);
CREATE INDEX idx_role_permissions_role      ON role_permissions(role_id);
CREATE INDEX idx_user_permissions_user      ON user_permissions(user_id);
CREATE INDEX idx_resources_user             ON resources(user_id);
CREATE INDEX idx_resources_course           ON resources(course_id);
CREATE INDEX idx_resources_type             ON resources(resource_type_id);
CREATE INDEX idx_resources_professor        ON resources(professor_id);
CREATE INDEX idx_resources_period           ON resources(academic_period_id);
CREATE INDEX idx_comments_resource          ON comments(resource_id);
CREATE INDEX idx_comments_user              ON comments(user_id);
CREATE INDEX idx_comments_parent            ON comments(parent_id);
CREATE INDEX idx_ratings_resource           ON ratings(resource_id);
CREATE INDEX idx_ratings_user               ON ratings(user_id);
CREATE INDEX idx_saved_resources_resource   ON saved_resources(resource_id);
CREATE INDEX idx_user_downloads_user        ON user_downloads(user_id);
CREATE INDEX idx_user_downloads_resource    ON user_downloads(resource_id);
CREATE INDEX idx_comment_votes_comment      ON comment_votes(comment_id);
CREATE INDEX idx_reports_reporter           ON reports(reporter_id);
CREATE INDEX idx_reports_reported_user      ON reports(reported_user_id);
CREATE INDEX idx_reports_resource           ON reports(resource_id);
CREATE INDEX idx_reports_comment            ON reports(comment_id);

-- === Búsqueda textual / lookup ===
CREATE INDEX idx_users_username             ON users(username);
CREATE INDEX idx_identities_email           ON identities(email);
CREATE INDEX idx_courses_code               ON courses(code);
CREATE INDEX idx_careers_code               ON careers(code);
CREATE INDEX idx_resources_title            ON resources(title);

-- === Filtros frecuentes ===
CREATE INDEX idx_resources_active           ON resources(is_active) WHERE is_active = TRUE;
CREATE INDEX idx_resources_created          ON resources(created_at DESC);
CREATE INDEX idx_reports_status_pending     ON reports(status) WHERE status = 'pending';

-- === GIN para búsqueda en array de tags ===
CREATE INDEX idx_resources_tags             ON resources USING GIN(tags);

-- === Auditoría ===
CREATE INDEX idx_audit_log_table            ON audit_log(table_name);
CREATE INDEX idx_audit_log_record           ON audit_log(record_id);
CREATE INDEX idx_audit_log_date             ON audit_log(changed_at DESC);